// export const USER_MODULE_ENDPOINTS = 'https://66caea284290b1c4f1990810.mockapi.io/users/create/'
export const USER_MODULE_ENDPOINTS = 'https://developer1.website/dev/caapis/dev/tests'
export const QUESTION_MODULE_ENDPOINTS_V2 = 'https://dev.lms.developer1.website/'
export const QUESTION_MODULE_ENDPOINTS = 'https://developer1.website/dev/caapis/dev/tests/create_question'
export const USER_MODULE_NEW_ENDPOINTS = 'https://developer1.website/dev/caapis/dev/user/list'
export const CATEGORY_MODULE_ENDPOINTS_CHILDREN = 'https://developer1.website/dev/caapis/dev/qb/categories'
export const CATEGORY_DATA = 'https://developer1.website/dev/caapis/dev/qb/category'
export const CATEGORY_DATA_V2 = 'https://local.lms.developer1.website/qb/category'
